### ISSUE TITLE
[Improvement][Flink]: Sink to Arctic with dynamically nodes scale-in/out

### ISSUE THREAD

**Issue by zstraw** [apache/incubator-amoro#1050]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Arctic nodes num can be configured in table properties, and it may be changed in any time.
Support changing it dynamically would bring a better experience for user.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
@zstraw #2 maybe useful
