### ISSUE TITLE
[Bug]: Column comment will be lost for Flink engine

### ISSUE THREAD

**Issue by JinsYin** [apache/incubator-amoro#1910]
## Flink SQL

```sql
CREATE TABLE p1_catalog1.db.tb1(
    id INT COMMENT 'myid' -- The column comment will be lost for Flink
);
```

![image](https://github.com/NetEase/amoro/assets/12714609/55e7a6da-b405-4ea0-ad75-10791a695458)

## Spark SQL

```sql
CREATE TABLE db.t1(
    id INT COMMENT 'myid' -- The column comment will be retained for Spark
);
```

![image](https://github.com/NetEase/amoro/assets/12714609/754d198e-f63c-4efb-a140-17032e4ec854)

### Affects Versions

v0.4.1

### What engines are you seeing the problem on?

Flink

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shidayang** [comment]
Thank you for reporting this issue. Could you fix it?

**Comment by huyuanfeng2018** [comment]
This seems to be a problem with iceberg flink catalog.Iceberg currently does not support using flinksql to create tables and specify field annotations.

**Comment by czy006** [comment]
Hi I willing to investigate this question and would like to ask what is the package name of the first picture cc @huyuanfeng2018

**Comment by baiyangtx** [comment]
It seems that you are accessing the metadata of the table directly through the Amoro Table Thrift API. What is the purpose of doing this? Note that the Table Thrift API may be deprecated in the future.

**Comment by JinsYin** [comment]
@baiyangtx I am obtaining table schema through the Thrift API, and the Flink version is 1.13.

**Comment by czy006** [comment]
> @baiyangtx I am using the Thrift API to retrieve detailed table structures and display them on the webpage. In addition, the Flink version is 1.13.
> 
> <img alt="image" width="1235" src="https://user-images.githubusercontent.com/12714609/268187917-3d9a9762-6f42-4400-add6-e56acd0c39fe.png">

I saw an issue about supporting parsing field comments in table creation statements. This function has not yet been implemented.

https://github.com/apache/iceberg/issues/8511

**Comment by czy006** [comment]
https://github.com/apache/iceberg/pull/9606,now iceberg version is 1.4.3,may be upgrade to 1.5.X to fix it

**Comment by JinsYin** [comment]
@czy006 Thanks, I will close this issue.
