### ISSUE TITLE
[Improvement]: Add maillist info in the `Welcome to Amoro` page

### ISSUE THREAD

**Issue by klion26** [apache/incubator-amoro#2701]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Add maillist info in the `Welcome to Amoro` page such as flink

![image](https://github.com/apache/incubator-amoro/assets/1425623/ad0c702c-c9a6-470f-a4d6-5ba513c334c0)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klion26** [comment]
cc @zhoujinsong . If this is valid, could you please give a hint which maillists should we add in the first time.
Currently, I just see this info in the [apache site](https://incubator.apache.org/projects/amoro.html)

![image](https://github.com/apache/incubator-amoro/assets/1425623/1985af8c-f8c1-41d7-9225-b54d925b703e)

**Comment by zhoujinsong** [comment]
Thanks a lot for bringing up this improvement. Adding email list information to the community guidelines is very necessary.

We may add the mailing list here: https://amoro.apache.org/join-community/
and the related source codes are here: https://github.com/apache/incubator-amoro-site/blob/master/amoro-site/content/community/join-community.md

IMO, we should show the subscribe/unsubscribe/archive entries for dev@amoro.apache.org and commits@amoro.apache.org, the archive entry only for private@amoro.apache.org, just like what iceberg did: https://iceberg.apache.org/community/#mailing-lists

**Comment by klion26** [comment]
thanks for the reply, will add this later

**Comment by klion26** [comment]
Addded the [pr](https://github.com/apache/incubator-amoro-site/pull/10)
